"""change db schema

Revision ID: 1428dfd2cdab
Revises: 34438bb53c72
Create Date: 2025-02-22 21:06:06.496994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app

# revision identifiers, used by Alembic.
revision: str = "1428dfd2cdab"
down_revision: Union[str, None] = "34438bb53c72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs_users_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_following", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_hided", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clubs_users_link_is_deleted"),
        "clubs_users_link",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "event_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("file", app.core.storage.fields.S3FileField(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_files_is_deleted"), "event_files", ["is_deleted"], unique=False
    )
    op.drop_index(
        "ix_clubs_followers_link_is_deleted", table_name="clubs_followers_link"
    )
    op.drop_table("clubs_followers_link")
    op.add_column("clubs", sa.Column("location_link", sa.String(), nullable=True))
    op.add_column(
        "event_registrations_link",
        sa.Column(
            "is_attended",
            sa.Boolean(),
            nullable=False,
            default=False,
            server_default="false",
        ),
    )
    op.add_column(
        "event_registrations_link",
        sa.Column("verification_code", sa.String(), nullable=True),
    )
    op.add_column(
        "event_registrations_link",
        sa.Column(
            "is_won",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    op.add_column(
        "event_registrations_link", sa.Column("position", sa.Integer(), nullable=True)
    )
    op.add_column("events", sa.Column("location_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "location_link")
    op.drop_column("event_registrations_link", "position")
    op.drop_column("event_registrations_link", "is_won")
    op.drop_column("event_registrations_link", "verification_code")
    op.drop_column("event_registrations_link", "is_attended")
    op.drop_column("clubs", "location_link")
    op.create_table(
        "clubs_followers_link",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_following", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name="clubs_followers_link_club_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="clubs_followers_link_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="clubs_followers_link_pkey"),
    )
    op.create_index(
        "ix_clubs_followers_link_is_deleted",
        "clubs_followers_link",
        ["is_deleted"],
        unique=False,
    )
    op.drop_index(op.f("ix_event_files_is_deleted"), table_name="event_files")
    op.drop_table("event_files")
    op.drop_index(op.f("ix_clubs_users_link_is_deleted"), table_name="clubs_users_link")
    op.drop_table("clubs_users_link")
    # ### end Alembic commands ###
