"""rename column additional info

Revision ID: 1927f940819e
Revises: 8c2153aad47c
Create Date: 2025-02-18 20:11:22.345941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1927f940819e'
down_revision: Union[str, None] = '8c2153aad47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations_link', sa.Column('additional_details', sa.JSON(), nullable=True))
    op.drop_column('event_registrations_link', 'additional_info')
    op.add_column('events', sa.Column('additional_details', sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('events', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('additional_info', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_column('events', 'additional_details')
    op.add_column('event_registrations_link', sa.Column('additional_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('event_registrations_link', 'additional_details')
    # ### end Alembic commands ###
