"""add full name in user profile table

Revision ID: 4d68b956a8c7
Revises: 737d8801a8a9
Create Date: 2025-02-25 15:30:24.670785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d68b956a8c7"
down_revision: Union[str, None] = "737d8801a8a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "full_name", sa.String(length=100), nullable=False, server_default=""
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "full_name")
    # ### end Alembic commands ###
