"""add event guidelines

Revision ID: 4e12cd720336
Revises: f825c6e24c61
Create Date: 2025-03-01 12:55:31.994692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e12cd720336'
down_revision: Union[str, None] = 'f825c6e24c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_guidelines', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_guidelines')
    # ### end Alembic commands ###
