"""add provider in user model

Revision ID: 5bec724524e1
Revises: 94c35c7cef24
Create Date: 2025-02-23 15:32:03.367448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bec724524e1"
down_revision: Union[str, None] = "94c35c7cef24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

signinproviders_enum = sa.Enum("google", "email", name="signinproviders")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    signinproviders_enum.create(op.get_bind())

    op.add_column(
        "users",
        sa.Column(
            "provider",
            sa.Enum("google", "email", name="signinproviders"),
            nullable=True,
        ),
    )
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("users", "provider")
    # ### end Alembic commands ###
