"""voluteer event_id club_id nullable

Revision ID: 68b144be5013
Revises: 703b6eae394a
Create Date: 2025-03-04 18:17:02.265607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '68b144be5013'
down_revision: Union[str, None] = '703b6eae394a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations_link', sa.Column('volunteer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_registrations_link', 'volunteers', ['volunteer_id'], ['id'])
    op.alter_column('volunteers', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('volunteers', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteers', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('volunteers', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'event_registrations_link', type_='foreignkey')
    op.drop_column('event_registrations_link', 'volunteer_id')
    # ### end Alembic commands ###
