"""update transactional tables ids to uuid

Revision ID: 703b6eae394a
Revises: f672ad52ad8a
Create Date: 2025-03-04 17:27:39.402003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = "703b6eae394a"
down_revision: Union[str, None] = "f672ad52ad8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add a new UUID column with a server default, allowing NULL initially
    op.add_column(
        "event_files",
        sa.Column(
            "id_new",
            sa.UUID(),
            nullable=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    op.add_column(
        "event_ratings_link",
        sa.Column(
            "id_new",
            sa.UUID(),
            nullable=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    op.add_column(
        "event_registrations_link",
        sa.Column(
            "id_new",
            sa.UUID(),
            nullable=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "id_new",
            sa.UUID(),
            nullable=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )

    # Step 2: Populate existing rows with UUIDs
    op.execute("UPDATE event_files SET id_new = gen_random_uuid();")
    op.execute("UPDATE event_ratings_link SET id_new = gen_random_uuid();")
    op.execute("UPDATE event_registrations_link SET id_new = gen_random_uuid();")
    op.execute("UPDATE notifications SET id_new = gen_random_uuid();")

    # Step 3: Set id_new to NOT NULL
    op.alter_column("event_files", "id_new", nullable=False)
    op.alter_column("event_ratings_link", "id_new", nullable=False)
    op.alter_column("event_registrations_link", "id_new", nullable=False)
    op.alter_column("notifications", "id_new", nullable=False)

    # Step 4: Drop the old INTEGER id column
    op.drop_column("event_files", "id")
    op.drop_column("event_ratings_link", "id")
    op.drop_column("event_registrations_link", "id")
    op.drop_column("notifications", "id")

    # Step 5: Rename id_new to id
    op.alter_column("event_files", "id_new", new_column_name="id")
    op.alter_column("event_ratings_link", "id_new", new_column_name="id")
    op.alter_column("event_registrations_link", "id_new", new_column_name="id")
    op.alter_column("notifications", "id_new", new_column_name="id")


def downgrade() -> None:
    raise NotImplementedError("Downgrade is not supported")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "notifications",
    #     "id",
    #     existing_type=sa.UUID(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "event_registrations_link",
    #     "id",
    #     existing_type=sa.UUID(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "event_ratings_link",
    #     "id",
    #     existing_type=sa.UUID(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "event_files",
    #     "id",
    #     existing_type=sa.UUID(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    # )
    # # ### end Alembic commands ###
