"""change avatar schema

Revision ID: 737d8801a8a9
Revises: 5bec724524e1
Create Date: 2025-02-23 17:54:47.807384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = "737d8801a8a9"
down_revision: Union[str, None] = "5bec724524e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_avatars",
        sa.Column("image", app.core.storage.fields.S3ImageField(), nullable=False),
    )
    op.drop_column("user_avatars", "content")
    op.drop_column("user_avatars", "icon_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_avatars",
        sa.Column(
            "icon_type",
            postgresql.ENUM("emoji", "url", name="useravatartypes"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_avatars",
        sa.Column(
            "content", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user_avatars", "image")
    # ### end Alembic commands ###
