"""add background task log table

Revision ID: 81d83575599d
Revises: 68b144be5013
Create Date: 2025-03-05 15:24:12.144306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d83575599d'
down_revision: Union[str, None] = '68b144be5013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_task_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('background_task_logs')
    # ### end Alembic commands ###
