"""remove event created by

Revision ID: 8c2153aad47c
Revises: aa030ee598b3
Create Date: 2025-02-18 20:07:11.074164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2153aad47c'
down_revision: Union[str, None] = 'aa030ee598b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_org_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_org_id_fkey', 'events', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###
