"""add contact field in club

Revision ID: 94c35c7cef24
Revises: 9df3e8f08220
Create Date: 2025-02-23 13:13:53.452991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c35c7cef24'
down_revision: Union[str, None] = '9df3e8f08220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('clubs', sa.Column('contact_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'contact_email')
    op.drop_column('clubs', 'contact_phone')
    # ### end Alembic commands ###
