"""add db schema

Revision ID: 9df3e8f08220
Revises: 
Create Date: 2025-02-23 12:14:03.988269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision: str = "9df3e8f08220"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interest_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "icon_type", sa.Enum("emoji", "url", name="interesticontype"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_interest_categories_is_deleted"),
        "interest_categories",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "school", "university", "college", "company", "other", name="orgtypes"
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=100), nullable=True),
        sa.Column("logo", sa.String(length=100), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_is_deleted"),
        "organizations",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "user_avatars",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column(
            "icon_type", sa.Enum("emoji", "url", name="useravatartypes"), nullable=False
        ),
        sa.Column("content", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_avatars_is_deleted"), "user_avatars", ["is_deleted"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("app_user", "club", "admin", name="usertypes"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", "user_type"),
        sa.UniqueConstraint("phone", "user_type"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    op.create_table(
        "clubs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("logo", app.core.storage.fields.S3ImageField(), nullable=True),
        sa.Column("about", sa.String(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.String(), nullable=True),
        sa.Column("location_link", sa.String(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("total_ratings", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("initial_password", sa.String(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clubs_is_deleted"), "clubs", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_clubs_slug"), "clubs", ["slug"], unique=True)
    op.create_table(
        "event_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "icon_type", sa.Enum("emoji", "url", name="useravatartypes"), nullable=True
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_categories_is_deleted"),
        "event_categories",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "interests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "icon_type", sa.Enum("emoji", "url", name="interesticontype"), nullable=True
        ),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["interest_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_interests_is_deleted"), "interests", ["is_deleted"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("whatsapp", sa.String(length=20), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("avatar_id", sa.Integer(), nullable=True),
        sa.Column("profile_pic", app.core.storage.fields.S3ImageField(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["avatar_id"],
            ["user_avatars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("whatsapp"),
    )
    op.create_index(
        op.f("ix_user_profiles_is_deleted"),
        "user_profiles",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "club_socials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("instagram", sa.String(length=255), nullable=True),
        sa.Column("linkedin", sa.String(length=255), nullable=True),
        sa.Column("youtube", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "is_deleted"),
    )
    op.create_index(
        op.f("ix_club_socials_is_deleted"), "club_socials", ["is_deleted"], unique=False
    )
    op.create_table(
        "club_users_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_following", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "user_id", "is_deleted"),
    )
    op.create_index(
        op.f("ix_club_users_link_is_deleted"),
        "club_users_link",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "clubs_interests_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clubs_interests_link_is_deleted"),
        "clubs_interests_link",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("poster", app.core.storage.fields.S3ImageField(), nullable=True),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("event_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("has_fee", sa.Boolean(), nullable=False),
        sa.Column("reg_fee", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("about", sa.String(), nullable=True),
        sa.Column("location_name", sa.String(), nullable=True),
        sa.Column("location_link", sa.String(), nullable=True),
        sa.Column("has_prize", sa.Boolean(), nullable=False),
        sa.Column("prize_amount", sa.Float(), nullable=True),
        sa.Column("contact_phone", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column("reg_startdate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reg_enddate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("additional_details", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["event_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_is_deleted"), "events", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=True)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_is_deleted"), "notes", ["is_deleted"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("from_club_id", sa.Integer(), nullable=True),
        sa.Column("from_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("read", "unread", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_is_deleted"),
        "notifications",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "user_interests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_interests_is_deleted"),
        "user_interests",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "event_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("file", app.core.storage.fields.S3FileField(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_files_is_deleted"), "event_files", ["is_deleted"], unique=False
    )
    op.create_table(
        "event_interests_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_interests_link_is_deleted"),
        "event_interests_link",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "event_ratings_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("review", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", "is_deleted"),
    )
    op.create_index(
        op.f("ix_event_ratings_link_is_deleted"),
        "event_ratings_link",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "event_registrations_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.String(length=60), nullable=False),
        sa.Column("is_attended", sa.Boolean(), nullable=False),
        sa.Column("attended_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_won", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", "is_deleted"),
    )
    op.create_index(
        op.f("ix_event_registrations_link_is_deleted"),
        "event_registrations_link",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_link_ticket_id"),
        "event_registrations_link",
        ["ticket_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_event_registrations_link_ticket_id"),
        table_name="event_registrations_link",
    )
    op.drop_index(
        op.f("ix_event_registrations_link_is_deleted"),
        table_name="event_registrations_link",
    )
    op.drop_table("event_registrations_link")
    op.drop_index(
        op.f("ix_event_ratings_link_is_deleted"), table_name="event_ratings_link"
    )
    op.drop_table("event_ratings_link")
    op.drop_index(
        op.f("ix_event_interests_link_is_deleted"), table_name="event_interests_link"
    )
    op.drop_table("event_interests_link")
    op.drop_index(op.f("ix_event_files_is_deleted"), table_name="event_files")
    op.drop_table("event_files")
    op.drop_index(op.f("ix_user_interests_is_deleted"), table_name="user_interests")
    op.drop_table("user_interests")
    op.drop_index(op.f("ix_notifications_is_deleted"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_notes_is_deleted"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.drop_index(op.f("ix_events_is_deleted"), table_name="events")
    op.drop_table("events")
    op.drop_index(
        op.f("ix_clubs_interests_link_is_deleted"), table_name="clubs_interests_link"
    )
    op.drop_table("clubs_interests_link")
    op.drop_index(op.f("ix_club_users_link_is_deleted"), table_name="club_users_link")
    op.drop_table("club_users_link")
    op.drop_index(op.f("ix_club_socials_is_deleted"), table_name="club_socials")
    op.drop_table("club_socials")
    op.drop_index(op.f("ix_user_profiles_is_deleted"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_interests_is_deleted"), table_name="interests")
    op.drop_table("interests")
    op.drop_index(op.f("ix_event_categories_is_deleted"), table_name="event_categories")
    op.drop_table("event_categories")
    op.drop_index(op.f("ix_clubs_slug"), table_name="clubs")
    op.drop_index(op.f("ix_clubs_is_deleted"), table_name="clubs")
    op.drop_table("clubs")
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_avatars_is_deleted"), table_name="user_avatars")
    op.drop_table("user_avatars")
    op.drop_index(op.f("ix_organizations_is_deleted"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(
        op.f("ix_interest_categories_is_deleted"), table_name="interest_categories"
    )
    op.drop_table("interest_categories")
    # ### end Alembic commands ###
