"""add schema for payments

Revision ID: a87892da3a2d
Revises: 4d68b956a8c7
Create Date: 2025-02-25 21:41:46.852790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87892da3a2d'
down_revision: Union[str, None] = '4d68b956a8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_webhook_logs_event_id'), 'razorpay_webhook_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_razorpay_webhook_logs_is_deleted'), 'razorpay_webhook_logs', ['is_deleted'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('created', 'attempted', 'paid', name='orderstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_index(op.f('ix_payment_orders_is_deleted'), 'payment_orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_orders_receipt'), 'payment_orders', ['receipt'], unique=True)
    op.create_table('payment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('created', 'authorized', 'captured', 'refunded', 'disputed', 'pending', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_logs_is_deleted'), 'payment_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_logs_razorpay_payment_id'), 'payment_logs', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_logs_razorpay_payment_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_is_deleted'), table_name='payment_logs')
    op.drop_table('payment_logs')
    op.drop_index(op.f('ix_payment_orders_receipt'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_is_deleted'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_razorpay_webhook_logs_is_deleted'), table_name='razorpay_webhook_logs')
    op.drop_index(op.f('ix_razorpay_webhook_logs_event_id'), table_name='razorpay_webhook_logs')
    op.drop_table('razorpay_webhook_logs')
    # ### end Alembic commands ###
