"""remove event created by

Revision ID: aa030ee598b3
Revises: bf205224829f
Create Date: 2025-02-18 19:56:10.164979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa030ee598b3'
down_revision: Union[str, None] = 'bf205224829f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_created_by_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('events_created_by_id_fkey', 'events', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###
