"""add max participants in events

Revision ID: aaa609dcd028
Revises: c394ca9a6991
Create Date: 2025-02-28 22:14:16.996772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa609dcd028'
down_revision: Union[str, None] = 'c394ca9a6991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('max_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'max_participants')
    # ### end Alembic commands ###
