"""add fields in event registration table and add guest user type

Revision ID: b4e18d502d38
Revises: 4e12cd720336
Create Date: 2025-03-02 14:04:56.046346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4e18d502d38"
down_revision: Union[str, None] = "4e12cd720336"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE usertypes ADD VALUE IF NOT EXISTS 'guest'")
    op.alter_column(
        "users",
        "user_type",
        existing_type=sa.Enum(name="usertypes"),
        nullable=False,
        type_=sa.Enum("app_user", "guest", "club", "admin", name="usertypes"),
    )

    op.add_column(
        "event_registrations_link",
        sa.Column("full_name", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "event_registrations_link",
        sa.Column("email", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "event_registrations_link",
        sa.Column("phone", sa.String(length=15), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_type",
        existing_type=sa.Enum("app_user", "club", "admin", name="usertypes"),
        nullable=False,
        type_=sa.Enum("app_user", "club", "admin", name="usertypes"),
    )
    op.drop_column("event_registrations_link", "phone")
    op.drop_column("event_registrations_link", "email")
    op.drop_column("event_registrations_link", "full_name")
    # ### end Alembic commands ###
