"""add contact phone to events schema

Revision ID: b675dd56f20e
Revises: ef592d8c28eb
Create Date: 2025-03-16 14:52:04.699271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'b675dd56f20e'
down_revision: Union[str, None] = 'ef592d8c28eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('contact_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'contact_name')
    # ### end Alembic commands ###
