"""add razorpay receipt field

Revision ID: c394ca9a6991
Revises: a87892da3a2d
Create Date: 2025-02-28 21:52:05.904024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c394ca9a6991'
down_revision: Union[str, None] = 'a87892da3a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_orders', sa.Column('razorpay_receipt', sa.String(), nullable=True))
    op.drop_index('ix_payment_orders_receipt', table_name='payment_orders')
    op.create_index(op.f('ix_payment_orders_receipt'), 'payment_orders', ['receipt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_orders_receipt'), table_name='payment_orders')
    op.create_index('ix_payment_orders_receipt', 'payment_orders', ['receipt'], unique=True)
    op.drop_column('payment_orders', 'razorpay_receipt')
    # ### end Alembic commands ###
