"""change db schema

Revision ID: d6954581596b
Revises: e08d67d3f322
Create Date: 2025-02-22 22:42:12.959526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6954581596b'
down_revision: Union[str, None] = 'e08d67d3f322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('from_club_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'clubs', ['from_club_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['from_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'from_user_id')
    op.drop_column('notifications', 'from_club_id')
    # ### end Alembic commands ###
