"""change db schema

Revision ID: e08d67d3f322
Revises: 5a6c0b2ad33b
Create Date: 2025-02-22 22:04:14.943699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e08d67d3f322'
down_revision: Union[str, None] = '5a6c0b2ad33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_users_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_following', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', 'is_deleted')
    )
    op.create_index(op.f('ix_club_users_link_is_deleted'), 'club_users_link', ['is_deleted'], unique=False)
    op.create_table('event_ratings_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', 'is_deleted')
    )
    op.create_index(op.f('ix_event_ratings_link_is_deleted'), 'event_ratings_link', ['is_deleted'], unique=False)
    op.drop_index('ix_clubs_users_link_is_deleted', table_name='clubs_users_link')
    op.drop_table('clubs_users_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs_users_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_following', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_hided', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='clubs_users_link_club_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='clubs_users_link_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clubs_users_link_pkey')
    )
    op.create_index('ix_clubs_users_link_is_deleted', 'clubs_users_link', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_event_ratings_link_is_deleted'), table_name='event_ratings_link')
    op.drop_table('event_ratings_link')
    op.drop_index(op.f('ix_club_users_link_is_deleted'), table_name='club_users_link')
    op.drop_table('club_users_link')
    # ### end Alembic commands ###
