"""test

Revision ID: e3748b54a2d7
Revises: efdd3bb2261c
Create Date: 2025-02-15 08:18:09.861386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3748b54a2d7'
down_revision: Union[str, None] = 'efdd3bb2261c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_categories', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_categories', 'users', ['created_by_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'event_categories', type_='foreignkey')
    op.drop_column('event_categories', 'created_by_id')
    # ### end Alembic commands ###
