"""add page view to events

Revision ID: ef592d8c28eb
Revises: 81d83575599d
Create Date: 2025-03-11 21:49:17.280324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = "ef592d8c28eb"
down_revision: Union[str, None] = "81d83575599d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_page_views",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            app.core.utils.db_fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.core.utils.db_fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at",
            app.core.utils.db_fields.TZAwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_page_views_is_deleted"),
        "event_page_views",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "events",
        sa.Column("page_views", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "page_views")
    op.drop_index(op.f("ix_event_page_views_is_deleted"), table_name="event_page_views")
    op.drop_table("event_page_views")
    # ### end Alembic commands ###
